// Drawn geography: coasts, lakes, rivers, relief marks and passes, already projected to pixels.
// Generated by the prototype's Python scripts (Natural Earth 10m and AWS Terrain Tiles).
import data from "../data/geo.json";

export interface River { d: string; r: number; n: string }
export interface Pass { id: string; name: string; desc: string; x: number; y: number }
/** [x, y, size, kind]: "h" hill, "m" mountain, "M" peak above 2,300 m */
export type Mark = [number, number, number, string];

export interface Geo {
  W: number;
  H: number;
  K: number;
  bbox: [number, number, number, number];
  land: string[];
  lakes: string[];
  rivers: River[];
  marks: Mark[];
  passes: Pass[];
}

export const GEO = data as unknown as Geo;
